/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccountResponseLinks } from './account-response-links';

/**
 * 
 * @export
 * @interface AccountResponse
 */
export interface AccountResponse {
    /**
     * Account Description
     * @type {string}
     * @memberof AccountResponse
     */
    'description'?: string;
    /**
     * 
     * @type {AccountResponseLinks}
     * @memberof AccountResponse
     */
    '_links'?: AccountResponseLinks;
    /**
     * Unique identifier of the account
     * @type {string}
     * @memberof AccountResponse
     */
    'id'?: string;
    /**
     * Account name
     * @type {string}
     * @memberof AccountResponse
     */
    'name'?: string;
    /**
     * URL of the Account\'s logo
     * @type {string}
     * @memberof AccountResponse
     */
    'logo_url'?: string;
    /**
     * List of domains associated to the Account
     * @type {Array<string>}
     * @memberof AccountResponse
     */
    'domains'?: Array<string>;
    /**
     * ID of the Account in an External system, such as your backoffice system or CRM
     * @type {string}
     * @memberof AccountResponse
     */
    'external_id'?: string;
    /**
     * Custom Attributes for this account
     * @type {object}
     * @memberof AccountResponse
     */
    'custom_fields'?: object;
    /**
     * Timestamp when the account was created
     * @type {number}
     * @memberof AccountResponse
     */
    'created_at'?: number;
    /**
     * Timestamp when the account was updated
     * @type {number}
     * @memberof AccountResponse
     */
    'updated_at'?: number;
}

