/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnalyticsExportResponseLinks } from './analytics-export-response-links';
import { AnalyticsFilters } from './analytics-filters';

/**
 * 
 * @export
 * @interface AnalyticsExportResponse
 */
export interface AnalyticsExportResponse {
    /**
     * 
     * @type {AnalyticsExportResponseLinks}
     * @memberof AnalyticsExportResponse
     */
    '_links'?: AnalyticsExportResponseLinks;
    /**
     * Status of the analytics
     * @type {string}
     * @memberof AnalyticsExportResponse
     */
    'status'?: AnalyticsExportResponseStatusEnum;
    /**
     * Number ranging from 0 to 100 corresponding to the percentage of the analytics processed.
     * @type {number}
     * @memberof AnalyticsExportResponse
     */
    'progress'?: number;
    /**
     * The URL from which the export data can be downloaded. Only displays after you make a GET request to the link included in the POST response.
     * @type {string}
     * @memberof AnalyticsExportResponse
     */
    'url'?: string;
    /**
     * The filename of the export with extension included. Only displays after you make a GET request to the link included in the POST response.
     * @type {string}
     * @memberof AnalyticsExportResponse
     */
    'filename'?: string;
    /**
     * Size (in bytes) of the export data. Only displays after you make a GET request to the link included in the POST response.
     * @type {number}
     * @memberof AnalyticsExportResponse
     */
    'size'?: number;
    /**
     * Timestamp (in seconds) at which the export was requested.
     * @type {number}
     * @memberof AnalyticsExportResponse
     */
    'created_at'?: number;
    /**
     * 
     * @type {AnalyticsFilters}
     * @memberof AnalyticsExportResponse
     */
    'filters'?: AnalyticsFilters;
}

type AnalyticsExportResponseStatusEnum = 'running' | 'done' | 'too_big' | 'failed'


