/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnalyticsReportResponseLinks } from './analytics-report-response-links';
import { AnalyticsScalar } from './analytics-scalar';

/**
 * 
 * @export
 * @interface AnalyticsReportResponse
 */
export interface AnalyticsReportResponse {
    /**
     * 
     * @type {AnalyticsReportResponseLinks}
     * @memberof AnalyticsReportResponse
     */
    '_links'?: AnalyticsReportResponseLinks;
    /**
     * Status of the report.
     * @type {string}
     * @memberof AnalyticsReportResponse
     */
    'status'?: AnalyticsReportResponseStatusEnum;
    /**
     * Number ranging from 0 to 100 corresponding to the percentage of the analytics processed.
     * @type {number}
     * @memberof AnalyticsReportResponse
     */
    'progress'?: number;
    /**
     * The metrics computed for the report.
     * @type {Array<AnalyticsScalar>}
     * @memberof AnalyticsReportResponse
     */
    'metrics'?: Array<AnalyticsScalar>;
}

type AnalyticsReportResponseStatusEnum = 'running' | 'done' | 'failed'


