/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Attachment } from './attachment';
import { CommentResponseLinks } from './comment-response-links';
import { TeammateResponse } from './teammate-response';

/**
 * 
 * @export
 * @interface CommentResponse
 */
export interface CommentResponse {
    /**
     * 
     * @type {CommentResponseLinks}
     * @memberof CommentResponse
     */
    '_links'?: CommentResponseLinks;
    /**
     * Unique identifier of the comment
     * @type {string}
     * @memberof CommentResponse
     */
    'id'?: string;
    /**
     * 
     * @type {TeammateResponse}
     * @memberof CommentResponse
     */
    'author'?: TeammateResponse;
    /**
     * Content of the comment
     * @type {string}
     * @memberof CommentResponse
     */
    'body'?: string;
    /**
     * Date at which the comment was posted
     * @type {number}
     * @memberof CommentResponse
     */
    'posted_at'?: number;
    /**
     * List of files attached to the comment
     * @type {Array<Attachment>}
     * @memberof CommentResponse
     */
    'attachments'?: Array<Attachment>;
}

