/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Contact
 */
export interface Contact {
    /**
     * Contact description
     * @type {string}
     * @memberof Contact
     */
    'description'?: string;
    /**
     * Contact name
     * @type {string}
     * @memberof Contact
     */
    'name'?: string;
    /**
     * Binary data of avatar. Must use `Content-Type: multipart/form-data` if specified. See [example](https://gist.github.com/hdornier/e04d04921032e98271f46ff8a539a4cb) or read more about [Attachments](https://dev.frontapp.com/docs/attachments-1).  Max 25 MB.
     * @type {Uint8Array | File | buffer.File}
     * @memberof Contact
     */
    'avatar'?: Uint8Array | File | buffer.File;
    /**
     * Whether or not the contact is marked as a spammer
     * @type {boolean}
     * @memberof Contact
     */
    'is_spammer'?: boolean;
    /**
     * List of all the links of the contact
     * @type {Array<string>}
     * @memberof Contact
     */
    'links'?: Array<string>;
    /**
     * List of all the group names the contact belongs to. It will automatically create missing groups
     * @type {Array<string>}
     * @memberof Contact
     */
    'group_names'?: Array<string>;
    /**
     * Custom field attributes for this contact. If you want to keep all custom fields the same when updating this resource, do not include any custom fields in the update. If you want to update custom fields, make sure to include all custom fields, not just the fields you want to add or update. If you send only the custom fields you want to update, the other custom fields will be erased. You can retrieve the existing custom fields before making the update to note the current fields.
     * @type {object}
     * @memberof Contact
     */
    'custom_fields'?: object;
}

