/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A message template that is used for pre-written responses
 * @export
 * @interface CreateSharedMessageTemplate
 */
export interface CreateSharedMessageTemplate {
    /**
     * Name of the message template
     * @type {string}
     * @memberof CreateSharedMessageTemplate
     */
    'name': string;
    /**
     * Subject of the message template. If not set, the name will be used to populate the subject.
     * @type {string}
     * @memberof CreateSharedMessageTemplate
     */
    'subject'?: string;
    /**
     * Body of the message template
     * @type {string}
     * @memberof CreateSharedMessageTemplate
     */
    'body': string;
    /**
     * ID of the message template folder to place this message template in
     * @type {string}
     * @memberof CreateSharedMessageTemplate
     */
    'folder_id'?: string;
    /**
     * The specific inboxes this template is available in. If unspecified or null, then it will be available in all inboxes. Array should be non-empty.
     * @type {Array<string>}
     * @memberof CreateSharedMessageTemplate
     */
    'inbox_ids'?: Array<string>;
    /**
     * Binary data of attached files. Must use `Content-Type: multipart/form-data` if specified. See [example](https://dev.frontapp.com/docs/attachments-1).  Max 25 MB.
     * @type {Array<Uint8Array | File | buffer.File>}
     * @memberof CreateSharedMessageTemplate
     */
    'attachments'?: Array<Uint8Array | File | buffer.File>;
}

