/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreateDraft
 */
export interface CreateDraft {
    /**
     * ID of the teammate on behalf of whom the draft will be created. Alternatively, you can supply the author ID as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
     * @type {string}
     * @memberof CreateDraft
     */
    'author_id': string;
    /**
     * List of recipient handles who will receive the message once the draft is sent
     * @type {Array<string>}
     * @memberof CreateDraft
     */
    'to'?: Array<string>;
    /**
     * List of recipient handles who will receive a copy of the message once the draft is sent
     * @type {Array<string>}
     * @memberof CreateDraft
     */
    'cc'?: Array<string>;
    /**
     * List of the recipient handles who will receive a blind copy of the message once the draft is sent
     * @type {Array<string>}
     * @memberof CreateDraft
     */
    'bcc'?: Array<string>;
    /**
     * Subject of the draft.
     * @type {string}
     * @memberof CreateDraft
     */
    'subject'?: string;
    /**
     * Body of the draft
     * @type {string}
     * @memberof CreateDraft
     */
    'body': string;
    /**
     * Body for the quote that the message is referencing. Only available on email channels.
     * @type {string}
     * @memberof CreateDraft
     */
    'quote_body'?: string;
    /**
     * Binary data of attached files. Must use `Content-Type: multipart/form-data` if specified. See [example](https://gist.github.com/hdornier/e04d04921032e98271f46ff8a539a4cb) or read more about [Attachments](https://dev.frontapp.com/docs/attachments-1). Max 25 MB.
     * @type {Array<Uint8Array | File | buffer.File>}
     * @memberof CreateDraft
     */
    'attachments'?: Array<Uint8Array | File | buffer.File>;
    /**
     * Mode of the draft to create. Can be \'private\' (draft is visible to the author only) or \'shared\' (draft is visible to all teammates with access to the conversation).
     * @type {string}
     * @memberof CreateDraft
     */
    'mode'?: CreateDraftModeEnum;
    /**
     * ID of the signature to attach to this draft. If null, no signature is attached.
     * @type {string}
     * @memberof CreateDraft
     */
    'signature_id'?: string;
    /**
     * Whether or not Front should try to resolve a signature for the message. Is ignored if signature_id is included. Default false;
     * @type {boolean}
     * @memberof CreateDraft
     */
    'should_add_default_signature'?: boolean;
}

type CreateDraftModeEnum = 'private' | 'shared'


