/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConversationResponse } from './conversation-response';
import { EventResponseLinks } from './event-response-links';
import { EventResponseSource } from './event-response-source';
import { EventResponseTarget } from './event-response-target';

/**
 * An event is created everytime something interesting is happening in Front.
 * @export
 * @interface EventResponse
 */
export interface EventResponse {
    /**
     * 
     * @type {EventResponseLinks}
     * @memberof EventResponse
     */
    '_links'?: EventResponseLinks;
    /**
     * Unique identifier of the event
     * @type {string}
     * @memberof EventResponse
     */
    'id'?: string;
    /**
     * Type of event
     * @type {string}
     * @memberof EventResponse
     */
    'type'?: EventResponseTypeEnum;
    /**
     * Date at which the event has been emitted
     * @type {number}
     * @memberof EventResponse
     */
    'emitted_at'?: number;
    /**
     * 
     * @type {EventResponseSource}
     * @memberof EventResponse
     */
    'source'?: EventResponseSource;
    /**
     * 
     * @type {EventResponseTarget}
     * @memberof EventResponse
     */
    'target'?: EventResponseTarget;
    /**
     * 
     * @type {ConversationResponse}
     * @memberof EventResponse
     */
    'conversation'?: ConversationResponse;
}

type EventResponseTypeEnum = 'assign' | 'unassign' | 'archive' | 'reopen' | 'trash' | 'restore' | 'reminder' | 'comment' | 'mention' | 'inbound' | 'outbound' | 'outbound_reply' | 'move' | 'forward' | 'tag' | 'untag' | 'sending_error' | 'message_bounce_error' | 'conversations_merged' | 'link_added' | 'link_removed' | 'custom_field_updated'


