/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ImportMessageMetadata
 */
export interface ImportMessageMetadata {
    /**
     * Reference which will be used to thread messages. If  omitted, Front threads by sender instead
     * @type {string}
     * @memberof ImportMessageMetadata
     */
    'thread_ref'?: string;
    /**
     * Determines if message is received (inbound) or sent (outbound) by you.
     * @type {boolean}
     * @memberof ImportMessageMetadata
     */
    'is_inbound': boolean;
    /**
     * Determines if message is archived after import.
     * @type {boolean}
     * @memberof ImportMessageMetadata
     */
    'is_archived'?: boolean;
    /**
     * Determines if rules should be skipped. `true` by default.
     * @type {boolean}
     * @memberof ImportMessageMetadata
     */
    'should_skip_rules'?: boolean;
}

