/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Data of the sender
 * @export
 * @interface ImportMessageSender
 */
export interface ImportMessageSender {
    /**
     * ID of the teammate who is the author of the message. Ignored if the message is inbound.
     * @type {string}
     * @memberof ImportMessageSender
     */
    'author_id'?: string;
    /**
     * Name of the sender
     * @type {string}
     * @memberof ImportMessageSender
     */
    'name'?: string;
    /**
     * Handle of the sender. It can be any string used to uniquely identify the sender
     * @type {string}
     * @memberof ImportMessageSender
     */
    'handle': string;
}

