/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { KnowledgeBaseResponseLinks } from './knowledge-base-response-links';

/**
 * 
 * @export
 * @interface KnowledgeBaseResponse
 */
export interface KnowledgeBaseResponse {
    /**
     * 
     * @type {KnowledgeBaseResponseLinks}
     * @memberof KnowledgeBaseResponse
     */
    '_links'?: KnowledgeBaseResponseLinks;
    /**
     * Unique identifier of the knowledge base
     * @type {string}
     * @memberof KnowledgeBaseResponse
     */
    'id'?: string;
    /**
     * Knowledge base name
     * @type {string}
     * @memberof KnowledgeBaseResponse
     */
    'name'?: string;
    /**
     * Status of the KB
     * @type {string}
     * @memberof KnowledgeBaseResponse
     */
    'status'?: KnowledgeBaseResponseStatusEnum;
    /**
     * Type of the KB
     * @type {string}
     * @memberof KnowledgeBaseResponse
     */
    'type'?: KnowledgeBaseResponseTypeEnum;
    /**
     * Locale of this requested KB
     * @type {string}
     * @memberof KnowledgeBaseResponse
     */
    'locale'?: KnowledgeBaseResponseLocaleEnum;
    /**
     * Timestamp when the knowledge base was created
     * @type {number}
     * @memberof KnowledgeBaseResponse
     */
    'created_at'?: number;
    /**
     * Timestamp when the knowledge base was updated
     * @type {number}
     * @memberof KnowledgeBaseResponse
     */
    'updated_at'?: number;
}

type KnowledgeBaseResponseStatusEnum = 'published' | 'unpublished'
type KnowledgeBaseResponseTypeEnum = 'internal' | 'external'
type KnowledgeBaseResponseLocaleEnum = 'fr' | 'en'


