/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { KnowledgeBaseCategorySlimResponseLinks } from './knowledge-base-category-slim-response-links';

/**
 * 
 * @export
 * @interface KnowledgeBaseCategorySlimResponse
 */
export interface KnowledgeBaseCategorySlimResponse {
    /**
     * 
     * @type {KnowledgeBaseCategorySlimResponseLinks}
     * @memberof KnowledgeBaseCategorySlimResponse
     */
    '_links'?: KnowledgeBaseCategorySlimResponseLinks;
    /**
     * Unique identifier of the knowledge base category
     * @type {string}
     * @memberof KnowledgeBaseCategorySlimResponse
     */
    'id'?: string;
    /**
     * Is the category hidden from navigation and breadcrumbs (topics are accessed as direct links)
     * @type {boolean}
     * @memberof KnowledgeBaseCategorySlimResponse
     */
    'is_hidden'?: boolean;
    /**
     * List of the locales the category supports
     * @type {Array<string>}
     * @memberof KnowledgeBaseCategorySlimResponse
     */
    'locales'?: Array<string>;
    /**
     * Timestamp when the category was created
     * @type {number}
     * @memberof KnowledgeBaseCategorySlimResponse
     */
    'created_at'?: number;
    /**
     * Timestamp when the category was updated
     * @type {number}
     * @memberof KnowledgeBaseCategorySlimResponse
     */
    'updated_at'?: number;
}

