/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { KnowledgeBaseCategoryResponseLinks } from './knowledge-base-category-response-links';

/**
 * 
 * @export
 * @interface KnowledgeBaseCategoryResponse
 */
export interface KnowledgeBaseCategoryResponse {
    /**
     * Description of the category
     * @type {string}
     * @memberof KnowledgeBaseCategoryResponse
     */
    'description'?: string;
    /**
     * 
     * @type {KnowledgeBaseCategoryResponseLinks}
     * @memberof KnowledgeBaseCategoryResponse
     */
    '_links'?: KnowledgeBaseCategoryResponseLinks;
    /**
     * Unique identifier of the knowledge base category
     * @type {string}
     * @memberof KnowledgeBaseCategoryResponse
     */
    'id'?: string;
    /**
     * Category name
     * @type {string}
     * @memberof KnowledgeBaseCategoryResponse
     */
    'name'?: string;
    /**
     * Is the category hidden
     * @type {boolean}
     * @memberof KnowledgeBaseCategoryResponse
     */
    'is_hidden'?: boolean;
    /**
     * Locale of this category
     * @type {string}
     * @memberof KnowledgeBaseCategoryResponse
     */
    'locale'?: KnowledgeBaseCategoryResponseLocaleEnum;
    /**
     * Timestamp when the category was created
     * @type {number}
     * @memberof KnowledgeBaseCategoryResponse
     */
    'created_at'?: number;
    /**
     * Timestamp when the category was updated
     * @type {number}
     * @memberof KnowledgeBaseCategoryResponse
     */
    'updated_at'?: number;
}

type KnowledgeBaseCategoryResponseLocaleEnum = 'fr' | 'en'


