/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReminderLinks } from './reminder-links';

/**
 * 
 * @export
 * @interface Reminder
 */
export interface Reminder {
    /**
     * 
     * @type {ReminderLinks}
     * @memberof Reminder
     */
    '_links'?: ReminderLinks;
    /**
     * Timestamp at which the conversation reminder has been created
     * @type {number}
     * @memberof Reminder
     */
    'created_at'?: number;
    /**
     * Timestamp that the conversation reminder has been scheduled for
     * @type {number}
     * @memberof Reminder
     */
    'scheduled_at'?: number;
    /**
     * Timestamp at which the conversation reminder has been updated
     * @type {number}
     * @memberof Reminder
     */
    'updated_at'?: number;
}

