/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RuleResponseLinks } from './rule-response-links';

/**
 * 
 * @export
 * @interface RuleResponse
 */
export interface RuleResponse {
    /**
     * 
     * @type {RuleResponseLinks}
     * @memberof RuleResponse
     */
    '_links'?: RuleResponseLinks;
    /**
     * Unique identifier of the rule
     * @type {string}
     * @memberof RuleResponse
     */
    'id'?: string;
    /**
     * Name of the rule
     * @type {string}
     * @memberof RuleResponse
     */
    'name'?: string;
    /**
     * List of the rule\'s actions description
     * @type {Array<string>}
     * @memberof RuleResponse
     */
    'actions'?: Array<string>;
    /**
     * Whether or not the rule is individual
     * @type {boolean}
     * @memberof RuleResponse
     */
    'is_private'?: boolean;
}

