/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TagResponseLinks } from './tag-response-links';

/**
 * A tag is a label that can be used to classify conversations.
 * @export
 * @interface TagResponse
 */
export interface TagResponse {
    /**
     * Description of the tag
     * @type {string}
     * @memberof TagResponse
     */
    'description'?: string;
    /**
     * 
     * @type {TagResponseLinks}
     * @memberof TagResponse
     */
    '_links'?: TagResponseLinks;
    /**
     * Unique identifier of the tag
     * @type {string}
     * @memberof TagResponse
     */
    'id'?: string;
    /**
     * Name of the tag
     * @type {string}
     * @memberof TagResponse
     */
    'name'?: string;
    /**
     * Highlight color of the tag.
     * @type {string}
     * @memberof TagResponse
     */
    'highlight'?: TagResponseHighlightEnum;
    /**
     * Whether or not the tag is individual
     * @type {boolean}
     * @memberof TagResponse
     */
    'is_private'?: boolean;
    /**
     * Whether the tag is visible in conversation lists.
     * @type {boolean}
     * @memberof TagResponse
     */
    'is_visible_in_conversation_lists'?: boolean;
    /**
     * Timestamp of tag create creation
     * @type {number}
     * @memberof TagResponse
     */
    'created_at'?: number;
    /**
     * Timestamp of the last tag update
     * @type {number}
     * @memberof TagResponse
     */
    'updated_at'?: number;
}

type TagResponseHighlightEnum = 'grey' | 'pink' | 'red' | 'orange' | 'yellow' | 'green' | 'light-blue' | 'blue' | 'purple'


