/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TeammateResponseLinks } from './teammate-response-links';

/**
 * A teammate is a user in Front.
 * @export
 * @interface TeammateResponse
 */
export interface TeammateResponse {
    /**
     * 
     * @type {TeammateResponseLinks}
     * @memberof TeammateResponse
     */
    '_links'?: TeammateResponseLinks;
    /**
     * Unique identifier of the teammate
     * @type {string}
     * @memberof TeammateResponse
     */
    'id'?: string;
    /**
     * Email address of the teammate
     * @type {string}
     * @memberof TeammateResponse
     */
    'email'?: string;
    /**
     * Username of the teammate (used for \"@\" mentions)
     * @type {string}
     * @memberof TeammateResponse
     */
    'username'?: string;
    /**
     * First name of the teammate
     * @type {string}
     * @memberof TeammateResponse
     */
    'first_name'?: string;
    /**
     * Last name of the teammate
     * @type {string}
     * @memberof TeammateResponse
     */
    'last_name'?: string;
    /**
     * Whether or not the teammate is an admin in your company
     * @type {boolean}
     * @memberof TeammateResponse
     */
    'is_admin'?: boolean;
    /**
     * Whether or not the teammate is available
     * @type {boolean}
     * @memberof TeammateResponse
     */
    'is_available'?: boolean;
    /**
     * Whether or not the teammate account has been blocked
     * @type {boolean}
     * @memberof TeammateResponse
     */
    'is_blocked'?: boolean;
    /**
     * Custom field attributes for this teammate
     * @type {object}
     * @memberof TeammateResponse
     */
    'custom_fields'?: object;
}

