/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InboxResponse } from './inbox-response';
import { TeamResponseLinks } from './team-response-links';
import { TeammateResponse } from './teammate-response';

/**
 * 
 * @export
 * @interface TeamResponse
 */
export interface TeamResponse {
    /**
     * 
     * @type {TeamResponseLinks}
     * @memberof TeamResponse
     */
    '_links'?: TeamResponseLinks;
    /**
     * Unique identifier of the team
     * @type {string}
     * @memberof TeamResponse
     */
    'id'?: string;
    /**
     * Name of the team
     * @type {string}
     * @memberof TeamResponse
     */
    'name'?: string;
    /**
     * List of the inboxes in the team
     * @type {Array<InboxResponse>}
     * @memberof TeamResponse
     */
    'inboxes'?: Array<InboxResponse>;
    /**
     * List of the teammates that have access to the team
     * @type {Array<TeammateResponse>}
     * @memberof TeamResponse
     */
    'members'?: Array<TeammateResponse>;
}

