/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ShiftIntervals } from './shift-intervals';

/**
 * 
 * @export
 * @interface UpdateShift
 */
export interface UpdateShift {
    /**
     * Name of the shift
     * @type {string}
     * @memberof UpdateShift
     */
    'name'?: string;
    /**
     * Color of the shift
     * @type {string}
     * @memberof UpdateShift
     */
    'color'?: UpdateShiftColorEnum;
    /**
     * A timezone name as defined in the IANA tz database
     * @type {string}
     * @memberof UpdateShift
     */
    'timezone'?: string;
    /**
     * 
     * @type {ShiftIntervals}
     * @memberof UpdateShift
     */
    'times'?: ShiftIntervals;
    /**
     * List of all the teammate ids who will be part of this shift. Alternatively, you can supply emails as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
     * @type {Array<string>}
     * @memberof UpdateShift
     */
    'teammate_ids'?: Array<string>;
}

type UpdateShiftColorEnum = 'black' | 'grey' | 'pink' | 'purple' | 'blue' | 'teal' | 'green' | 'yellow' | 'orange' | 'red'


