/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UpdateTag
 */
export interface UpdateTag {
    /**
     * Description of the tag
     * @type {string}
     * @memberof UpdateTag
     */
    'description'?: string;
    /**
     * Name of the tag
     * @type {string}
     * @memberof UpdateTag
     */
    'name'?: string;
    /**
     * Highlight color of the tag.
     * @type {string}
     * @memberof UpdateTag
     */
    'highlight'?: UpdateTagHighlightEnum;
    /**
     * ID of the parent of this tag. Set to `null` to remove  the parent tag.
     * @type {string}
     * @memberof UpdateTag
     */
    'parent_tag_id'?: string;
    /**
     * Whether the tag is visible in conversation lists.
     * @type {boolean}
     * @memberof UpdateTag
     */
    'is_visible_in_conversation_lists'?: boolean;
}

type UpdateTagHighlightEnum = 'grey' | 'pink' | 'red' | 'orange' | 'yellow' | 'green' | 'light-blue' | 'blue' | 'purple'


