/*
Core API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UpdateTeammate
 */
export interface UpdateTeammate {
    /**
     * New username. It must be unique and can only contains lowercase letters, numbers and underscores.
     * @type {string}
     * @memberof UpdateTeammate
     */
    'username'?: string;
    /**
     * New first name
     * @type {string}
     * @memberof UpdateTeammate
     */
    'first_name'?: string;
    /**
     * New last name
     * @type {string}
     * @memberof UpdateTeammate
     */
    'last_name'?: string;
    /**
     * New availability status
     * @type {boolean}
     * @memberof UpdateTeammate
     */
    'is_available'?: boolean;
    /**
     * Custom field attributes for this teammate. If you want to keep all custom fields the same when updating this resource, do not include any custom fields in the update. If you want to update custom fields, make sure to include all custom fields, not just the fields you want to add or update. If you send only the custom fields you want to update, the other custom fields will be erased. You can retrieve the existing custom fields before making the update to note the current fields.
     * @type {object}
     * @memberof UpdateTeammate
     */
    'custom_fields'?: object;
}

